export const themes = {
  light: {
    "--color-element": "#e6f1f5",
    "--color-background": "#dde7eb",
    "--color-text": "#303436",
    "--font-family": '"Inter", sans-serif',
  },
  dark: {
    "--color-element": "#42413d",
    "--color-background": "#21211f",
    "--color-text": "#EEEEEE",
    "--font-family": '"Inter", sans-serif',
  },
  nord: {
    "--color-element": "#37424a",
    "--color-background": "#2a3339",
    "--color-text": "#c5baa0",
    "--font-family": '"Inter", sans-serif',
  },
  everforest: {
    "--color-element": "#313d42",
    "--color-background": "#1f272b",
    "--color-text": "#d0c3a8",
    "--font-family": '"Inter", sans-serif',
  },
  candy: {
    "--color-element": "#C39898",
    "--color-background": "#987070",
    "--color-text": "#F1E5D1",
    "--font-family": '"Inter", sans-serif',
  },
  sails: {
    "--color-element": "#3E5879",
    "--color-background": "#213555",
    "--color-text": "#F5EFE7",
    "--font-family": '"Inter", sans-serif',
  },
  terminal: {
    "--color-element": "#626262",
    "--color-background": "#292929",
    "--color-text": "#f1bf6d",
    "--font-family": '"JetBrains Mono", sans-serif',
  },
  dracula: {
    "--color-element": "#44475a",
    "--color-background": "#282a36",
    "--color-text": "#f8f8f2",
    "--font-family": '"Inter", sans-serif',
  },
  gruvbox: {
    "--color-element": "#504945",
    "--color-background": "#282828",
    "--color-text": "#ebdbb2",
    "--font-family": '"Inter", sans-serif',
  },
  monokai: {
    "--color-element": "#49483e",
    "--color-background": "#272822",
    "--color-text": "#f8f8f2",
    "--font-family": '"Inter", sans-serif',
  },
  catppuccin: {
    "--color-element": "#585b70",
    "--color-background": "#1e1e2e",
    "--color-text": "#cdd6f4",
    "--font-family": '"Inter", sans-serif',
  },
  github: {
    "--color-element": "#e5e5e5",
    "--color-background": "#ffffff",
    "--color-text": "#24292e",
    "--font-family": '"Inter", sans-serif',
  },
  githubDark: {
    "--color-element": "#30363d",
    "--color-background": "#0d1117",
    "--color-text": "#c9d1d9",
    "--font-family": '"Inter", sans-serif',
  },
  material: {
    "--color-element": "#37474f",
    "--color-background": "#263238",
    "--color-text": "#eceff1",
    "--font-family": '"Inter", sans-serif',
  },
  ayu: {
    "--color-element": "#465361",
    "--color-background": "#0f1419",
    "--color-text": "#e6e1cf",
    "--font-family": '"Inter", sans-serif',
  },
  cyberpunk: {
    "--color-element": "#3d375e",
    "--color-background": "#0c0e15",
    "--color-text": "#00f0ff",
    "--font-family": '"JetBrains Mono", sans-serif',
  },
  matrix: {
    "--color-element": "#0a2e0a",
    "--color-background": "#000000",
    "--color-text": "#00ff41",
    "--font-family": '"JetBrains Mono", sans-serif',
  },
  espresso: {
    "--color-element": "#3a3226",
    "--color-background": "#221d15",
    "--color-text": "#d1c7b7",
    "--font-family": '"Inter", sans-serif',
  },
};
